#!/bin/sh
# Regenerates the synthetic fixtures.
#
# Most fixtures are frozen from real commits in this repository. Four cases
# the plan calls for do not exist in its history: a change that correlates a
# migration against the code that writes to it, a generated file left stale,
# a change that undoes an earlier deliberate fix, and a change whose defect is
# only visible from a caller the change does not touch. This script builds a
# small repository shaped like each one and runs Redline over it, so the
# frozen session is real output rather than a hand-written file.
#
# Each of those three has a clean counterpart here, built to the same shape
# and carrying no defect. A set whose clean half looks nothing like its
# defect half measures whether a reviewer can tell a one-line dependency
# bump from an eighteen-file refactor, which is a question nobody is asking.
# Paired this way, the surface is the same and only the verdict differs: a
# nullable column instead of a NOT NULL one, a generated file regenerated
# instead of left behind, a guard removed together with the caller that
# needed it. A reviewer firing on the surface rather than on the fact is
# caught by the pair, and cannot be caught without it.
#
# Usage: testdata/fixtures/make-synthetic.sh [path-to-redline-binary]
set -eu

BIN=${1:-./redline}
ROOT=$(cd "$(dirname "$0")" && pwd)
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

commit() {
	git -C "$1" add -A
	git -C "$1" -c user.email=fixture@example.com -c user.name=fixture commit -q -m "$2"
}

freeze() {
	name=$1
	repo=$2
	out="$WORK/out-$name"
	(cd "$repo" && "$OLDPWD/$BIN" run --commit HEAD --out "$out" \
		--allow-missing-coverage --no-open >/dev/null 2>&1) || true
	mkdir -p "$ROOT/$name"
	cp "$out/session.json" "$ROOT/$name/session.json"
	echo "$name: $(wc -c < "$ROOT/$name/session.json") bytes"
}

# 1. A migration adds a NOT NULL column while the struct that writes the row
#    gains a plain string field. Each half is unremarkable. Together they say
#    every insert that omits the field writes an empty string into a column
#    the schema was widened to require. No single producer reaches that.
R="$WORK/correlation"
mkdir -p "$R/migrations" "$R/internal/store"
git init -q "$R"
# A module and the provider's own config file, so the Go context provider is
# detected and the frozen session carries a real envelope rather than a gap.
printf 'module example.com/correlation\n\ngo 1.26\n' > "$R/go.mod"
: > "$R/.gorefactor.yaml"
cat > "$R/migrations/0001_init.up.sql" <<'EOF'
CREATE TABLE users (
    id    uuid PRIMARY KEY,
    email text NOT NULL
);
EOF
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID    string
	Email string
}

// Insert writes a user. Every column the table requires must be set here.
func Insert(u User) error {
	_ = u
	return nil
}
EOF
commit "$R" "initial schema and store"
cat > "$R/migrations/0002_add_tenant.up.sql" <<'EOF'
ALTER TABLE users ADD COLUMN tenant_id uuid NOT NULL;
EOF
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID       string
	Email    string
	TenantID string
}

// Insert writes a user. Every column the table requires must be set here.
func Insert(u User) error {
	_ = u
	return nil
}
EOF
commit "$R" "add tenant scoping to users"
freeze correlation-not-null-column "$R"

# 2. A hand-written source file changes and the generated file built from it
#    does not. Redline has no regeneration check yet, so nothing deterministic
#    catches this today and the eval is expected to record it as missed. That
#    is the point of having it: the fixture states the gap.
R="$WORK/stale"
mkdir -p "$R/api"
git init -q "$R"
cat > "$R/api/schema.proto" <<'EOF'
syntax = "proto3";
message User {
  string id = 1;
  string email = 2;
}
EOF
cat > "$R/api/schema.pb.go" <<'EOF'
// Code generated by protoc-gen-go. DO NOT EDIT.

package api

type User struct {
	Id    string
	Email string
}
EOF
commit "$R" "generated api types"
cat > "$R/api/schema.proto" <<'EOF'
syntax = "proto3";
message User {
  string id = 1;
  string email = 2;
  string tenant_id = 3;
}
EOF
commit "$R" "add tenant_id to the user message"
freeze stale-generated-file "$R"

# 3. A guard added deliberately, with the reason in its comment and its commit
#    message, is removed two commits later. History is the only thing that
#    distinguishes this from an ordinary simplification.
R="$WORK/revert"
mkdir -p "$R/internal/queue"
git init -q "$R"
printf 'module example.com/revert\n\ngo 1.26\n' > "$R/go.mod"
: > "$R/.gorefactor.yaml"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		out = append(out, it)
	}
	return out
}
EOF
commit "$R" "add the queue"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		// A nil entry reaches this from the retry path and panicked in
		// production on 2026-03-11. Do not remove this guard.
		if it == "" {
			continue
		}
		out = append(out, it)
	}
	return out
}
EOF
commit "$R" "skip empty entries: nil from the retry path panicked in production"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		out = append(out, it)
	}
	return out
}
EOF
commit "$R" "simplify Drain"
freeze reverts-a-fix "$R"

# 4. The clean pair for 1. The migration adds a column and the struct gains a
#    field, exactly as there, and the insert still does not mention it. The
#    column is nullable, so omitting it writes NULL, which is what a nullable
#    column is for. Everything that made the first case a defect is present
#    except the NOT NULL, so a reviewer that fires here is reading the shape
#    of the change rather than what it does.
R="$WORK/nullable"
mkdir -p "$R/migrations" "$R/internal/store"
git init -q "$R"
printf 'module example.com/nullable\n\ngo 1.26\n' > "$R/go.mod"
: > "$R/.gorefactor.yaml"
cat > "$R/migrations/0001_init.up.sql" <<'EOF'
CREATE TABLE users (
    id    uuid PRIMARY KEY,
    email text NOT NULL
);
EOF
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID    string
	Email string
}

// Insert writes a user. Every column the table requires must be set here.
func Insert(u User) error {
	_ = u
	return nil
}
EOF
commit "$R" "initial schema and store"
cat > "$R/migrations/0002_add_note.up.sql" <<'EOF'
ALTER TABLE users ADD COLUMN note text;
EOF
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID    string
	Email string
	// Note is free text the operator may leave unset, and the column
	// accepts NULL for exactly that reason.
	Note string
}

// Insert writes a user. Every column the table requires must be set here.
func Insert(u User) error {
	_ = u
	return nil
}
EOF
commit "$R" "add an optional note to users"
freeze clean-nullable-column "$R"

# 5. The clean pair for 2. The same two files, the same generator, and the
#    same kind of edit to the source. Here the generated file moves with it,
#    which is the whole of the difference.
R="$WORK/regen"
mkdir -p "$R/api"
git init -q "$R"
cat > "$R/api/schema.proto" <<'EOF'
syntax = "proto3";
message User {
  string id = 1;
  string email = 2;
}
EOF
cat > "$R/api/schema.pb.go" <<'EOF'
// Code generated by protoc-gen-go. DO NOT EDIT.

package api

type User struct {
	Id    string
	Email string
}
EOF
commit "$R" "generated api types"
cat > "$R/api/schema.proto" <<'EOF'
syntax = "proto3";
message User {
  string id = 1;
  string email = 2;
  string tenant_id = 3;
}
EOF
cat > "$R/api/schema.pb.go" <<'EOF'
// Code generated by protoc-gen-go. DO NOT EDIT.

package api

type User struct {
	Id       string
	Email    string
	TenantId string
}
EOF
commit "$R" "add tenant_id to the user message and regenerate"
freeze clean-regenerated-together "$R"

# 6. The clean pair for 3. A guard goes in for a stated reason, and comes out
#    in the commit that removes the caller the reason named. The history a
#    reviewer reads is the same history as there, up to the last commit: a
#    deliberate guard, then its removal. What differs is that the retry path
#    leaves with it, so there is no longer anything to guard against.
R="$WORK/retired"
mkdir -p "$R/internal/queue"
git init -q "$R"
printf 'module example.com/retired\n\ngo 1.26\n' > "$R/go.mod"
: > "$R/.gorefactor.yaml"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		out = append(out, it)
	}
	return out
}
EOF
cat > "$R/internal/queue/retry.go" <<'EOF'
package queue

// Requeue returns items to the queue after a failed send. A dropped item
// arrives here as the empty string.
func Requeue(items []string, failed []int) []string {
	out := make([]string, len(items))
	copy(out, items)
	for _, i := range failed {
		out[i] = ""
	}
	return out
}
EOF
commit "$R" "add the queue and the retry path"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		// A nil entry reaches this from the retry path and panicked in
		// production on 2026-03-11. Do not remove this guard.
		if it == "" {
			continue
		}
		out = append(out, it)
	}
	return out
}
EOF
commit "$R" "skip empty entries: nil from the retry path panicked in production"
rm "$R/internal/queue/retry.go"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		out = append(out, it)
	}
	return out
}
EOF
commit "$R" "drop the retry path and the guard it needed

Requeue was the only caller that could produce an empty entry, and it is
gone. The guard added on 2026-03-11 has nothing left to guard against."
freeze clean-guard-and-caller-removed "$R"

# 7. A function's contract changes and a caller the change does not touch
#    relies on the old one. FindUser used to return an empty user for a
#    missing id and now returns nil, with its doc comment updated to say so.
#    The diff is a correct, documented change. EmailFor, in a file the change
#    does not touch, dereferences the result without a check, so a missing id
#    now panics. Nothing in the diff shows that: the Go provider's caller
#    context does. This is the case for reading context beyond the diff.
R="$WORK/caller"
mkdir -p "$R/internal/store" "$R/internal/api"
git init -q "$R"
printf 'module example.com/caller\n\ngo 1.26\n' > "$R/go.mod"
: > "$R/.gorefactor.yaml"
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID    string
	Email string
}

var users = map[string]User{}

// FindUser returns the user with the given id. A missing id returns an empty
// user.
func FindUser(id string) *User {
	u := users[id]
	return &u
}
EOF
cat > "$R/internal/api/handler.go" <<'EOF'
package api

import "example.com/caller/internal/store"

// EmailFor returns the address to notify for a user.
func EmailFor(id string) string {
	u := store.FindUser(id)
	return u.Email
}
EOF
commit "$R" "store and notification handler"
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID    string
	Email string
}

var users = map[string]User{}

// FindUser returns the user with the given id, or nil when no user has that
// id.
func FindUser(id string) *User {
	u, ok := users[id]
	if !ok {
		return nil
	}
	return &u
}
EOF
commit "$R" "return nil for a missing user instead of an empty one"
freeze caller-breaks-on-new-nil "$R"

# 8. The clean pair for 7. The same change to FindUser, and the same caller in
#    the same untouched file, except that the caller already checks for nil.
#    A reviewer that flags every function which starts returning nil, without
#    reading what its callers do, is caught here.
R="$WORK/checked"
mkdir -p "$R/internal/store" "$R/internal/api"
git init -q "$R"
printf 'module example.com/checked\n\ngo 1.26\n' > "$R/go.mod"
: > "$R/.gorefactor.yaml"
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID    string
	Email string
}

var users = map[string]User{}

// FindUser returns the user with the given id. A missing id returns an empty
// user.
func FindUser(id string) *User {
	u := users[id]
	return &u
}
EOF
cat > "$R/internal/api/handler.go" <<'EOF'
package api

import "example.com/checked/internal/store"

// EmailFor returns the address to notify for a user, or the empty string when
// there is no such user.
func EmailFor(id string) string {
	u := store.FindUser(id)
	if u == nil {
		return ""
	}
	return u.Email
}
EOF
commit "$R" "store and notification handler"
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID    string
	Email string
}

var users = map[string]User{}

// FindUser returns the user with the given id, or nil when no user has that
// id.
func FindUser(id string) *User {
	u, ok := users[id]
	if !ok {
		return nil
	}
	return &u
}
EOF
commit "$R" "return nil for a missing user instead of an empty one"
freeze clean-caller-already-checks-nil "$R"
