#!/bin/sh
# Regenerates the synthetic fixtures.
#
# Most fixtures are frozen from real commits in this repository. Three cases
# the plan calls for do not exist in its history: a change that correlates a
# migration against the code that writes to it, a generated file left stale,
# and a change that undoes an earlier deliberate fix. This script builds a
# small repository shaped like each one and runs Redline over it, so the
# frozen session is real output rather than a hand-written file.
#
# Usage: testdata/fixtures/make-synthetic.sh [path-to-redline-binary]
set -eu

BIN=${1:-./redline}
ROOT=$(cd "$(dirname "$0")" && pwd)
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

commit() {
	git -C "$1" add -A
	git -C "$1" -c user.email=fixture@example.com -c user.name=fixture commit -q -m "$2"
}

freeze() {
	name=$1
	repo=$2
	out="$WORK/out-$name"
	(cd "$repo" && "$OLDPWD/$BIN" run --commit HEAD --out "$out" \
		--allow-missing-coverage --no-open >/dev/null 2>&1) || true
	mkdir -p "$ROOT/$name"
	cp "$out/session.json" "$ROOT/$name/session.json"
	echo "$name: $(wc -c < "$ROOT/$name/session.json") bytes"
}

# 1. A migration adds a NOT NULL column while the struct that writes the row
#    gains a plain string field. Each half is unremarkable. Together they say
#    every insert that omits the field writes an empty string into a column
#    the schema was widened to require. No single producer reaches that.
R="$WORK/correlation"
mkdir -p "$R/migrations" "$R/internal/store"
git -C "$R" init -q 2>/dev/null || git init -q "$R"
cat > "$R/migrations/0001_init.up.sql" <<'EOF'
CREATE TABLE users (
    id    uuid PRIMARY KEY,
    email text NOT NULL
);
EOF
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID    string
	Email string
}

// Insert writes a user. Every column the table requires must be set here.
func Insert(u User) error {
	_ = u
	return nil
}
EOF
commit "$R" "initial schema and store"
cat > "$R/migrations/0002_add_tenant.up.sql" <<'EOF'
ALTER TABLE users ADD COLUMN tenant_id uuid NOT NULL;
EOF
cat > "$R/internal/store/user.go" <<'EOF'
package store

// User is one row of the users table.
type User struct {
	ID       string
	Email    string
	TenantID string
}

// Insert writes a user. Every column the table requires must be set here.
func Insert(u User) error {
	_ = u
	return nil
}
EOF
commit "$R" "add tenant scoping to users"
freeze correlation-not-null-column "$R"

# 2. A hand-written source file changes and the generated file built from it
#    does not. Redline has no regeneration check yet, so nothing deterministic
#    catches this today and the eval is expected to record it as missed. That
#    is the point of having it: the fixture states the gap.
R="$WORK/stale"
mkdir -p "$R/api"
git init -q "$R"
cat > "$R/api/schema.proto" <<'EOF'
syntax = "proto3";
message User {
  string id = 1;
  string email = 2;
}
EOF
cat > "$R/api/schema.pb.go" <<'EOF'
// Code generated by protoc-gen-go. DO NOT EDIT.

package api

type User struct {
	Id    string
	Email string
}
EOF
commit "$R" "generated api types"
cat > "$R/api/schema.proto" <<'EOF'
syntax = "proto3";
message User {
  string id = 1;
  string email = 2;
  string tenant_id = 3;
}
EOF
commit "$R" "add tenant_id to the user message"
freeze stale-generated-file "$R"

# 3. A guard added deliberately, with the reason in its comment and its commit
#    message, is removed two commits later. History is the only thing that
#    distinguishes this from an ordinary simplification.
R="$WORK/revert"
mkdir -p "$R/internal/queue"
git init -q "$R"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		out = append(out, it)
	}
	return out
}
EOF
commit "$R" "add the queue"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		// A nil entry reaches this from the retry path and panicked in
		// production on 2026-03-11. Do not remove this guard.
		if it == "" {
			continue
		}
		out = append(out, it)
	}
	return out
}
EOF
commit "$R" "skip empty entries: nil from the retry path panicked in production"
cat > "$R/internal/queue/queue.go" <<'EOF'
package queue

// Drain empties the queue.
func Drain(items []string) []string {
	var out []string
	for _, it := range items {
		out = append(out, it)
	}
	return out
}
EOF
commit "$R" "simplify Drain"
freeze reverts-a-fix "$R"
