package packet

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGeneratedByNameOnlyMatchesWhatGeneratorsProduce(t *testing.T) {
	generated := []string{
		"go.sum",
		"web/package-lock.json",
		"web/pnpm-lock.yaml",
		"Cargo.lock",
		"vendor/github.com/x/y/z.go",
		"internal/api/oas_handlers_gen.go",
		"internal/pb/service.pb.go",
		"internal/pb/service_grpc.pb.go",
		"internal/db/queries.sql.go",
		"api/zz_generated.deepcopy.go",
		"web/dist/app.min.js",
		"web/dist/app.css.map",
	}
	for _, path := range generated {
		if generatedByName(path) == "" {
			t.Errorf("%s: expected to be recognized as generated", path)
		}
	}

	// Hand-written files a loose rule would eat. Each of these has been a real
	// false positive in some generated-file heuristic.
	handWritten := []string{
		"go.mod",
		"internal/db/models.go",
		"internal/api/handlers.go",
		"internal/api/openapi.yaml",
		"web/src/api.ts",
		"cmd/redline/main.go",
		"internal/generator/generator.go",
		"docs/generated-code.md",
		"vendoring.md",
	}
	for _, path := range handWritten {
		if why := generatedByName(path); why != "" {
			t.Errorf("%s: hand-written file excluded as %q", path, why)
		}
	}
}

func TestGeneratedByHeaderReadsTheGeneratorsOwnClaim(t *testing.T) {
	dir := t.TempDir()
	write := func(name, body string) {
		if err := os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	write("marked.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
	write("tagged.ts", "/* @generated */\nexport const x = 1;\n")
	write("hash.py", "# Code generated by protoc. DO NOT EDIT.\nx = 1\n")
	write("plain.go", "package db\n\nfunc Real() {}\n")
	// The words appear, but far enough down that a generator did not write it.
	write("late.go", "package db\n"+spaces(5000)+"\n// Code generated DO NOT EDIT\n")

	for _, name := range []string{"marked.go", "tagged.ts", "hash.py"} {
		if !generatedByHeader(dir, name) {
			t.Errorf("%s: expected the generated marker to be found", name)
		}
	}
	if generatedByHeader(dir, "plain.go") {
		t.Error("plain.go: hand-written file read as generated")
	}
	if generatedByHeader(dir, "late.go") {
		t.Error("late.go: marker past the header window should not count")
	}
	if generatedByHeader(dir, "missing.go") {
		t.Error("a file that cannot be opened is not evidence of generation")
	}
}

func TestGeneratedSplitsAndExplainsEveryExclusion(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "marked.go"), []byte("// Code generated by ogen. DO NOT EDIT.\npackage x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "hand.go"), []byte("package x\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	paths := []string{"go.sum", "hand.go", "marked.go", "attr.txt"}
	attrs := map[string]bool{"attr.txt": true}

	kept, generated := Generated(dir, paths, attrs)

	if len(kept) != 1 || kept[0] != "hand.go" {
		t.Fatalf("kept = %v, want [hand.go]", kept)
	}
	if len(generated) != 3 {
		t.Fatalf("generated = %v, want go.sum, marked.go and attr.txt", generated)
	}
	for _, path := range generated {
		if GeneratedReason(dir, path, attrs) == "" {
			t.Errorf("%s: excluded without a stated reason", path)
		}
	}
	if got := GeneratedReason(dir, "attr.txt", attrs); got != "marked linguist-generated" {
		t.Errorf("attr.txt reason = %q, want the gitattributes reason", got)
	}
	if got := GeneratedReason(dir, "hand.go", attrs); got != "" {
		t.Errorf("hand.go reason = %q, want none", got)
	}
}

func spaces(n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = ' '
	}
	return string(b)
}
